# Generated by Django 4.2.7 on 2023-12-25 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_myuser_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='avatar',
        ),
    ]
